name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: "5.1.5"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: test
      run: |
        luac -p $(find . -name '*.lua' -print)
